namespace AlloyClient.Networking.Enums;

public enum StatsType : byte {
    MaximumHp,
    Hp,
    Size,
    MaximumMp,
    Mp,
    NextLevelXp,
    Experience,
    Level,
    Inventory0,
    Inventory1,
    Inventory2,
    Inventory3,
    Inventory4,
    Inventory5,
    Inventory6,
    Inventory7,
    Inventory8,
    Inventory9,
    Inventory10,
    Inventory11,
    Attack,
    Defense,
    Speed,
    Vitality,
    Wisdom,
    Dexterity,
    Condition1,
    NumStars,
    Name,
    Texture1,
    Texture2,
    MerchandiseType,
    MerchandisePrice,
    Credits,
    Active,
    AccountId,
    Fame,
    MerchandiseCurrency,
    Connect,
    MerchandiseCount,
    MerchandiseMinsLeft,
    MerchandiseDiscount,
    MerchandiseRankReq,
    CharFame,
    NextClassQuestFame,
    LegendaryRank,
    SinkLevel,
    AltTexture,
    Guild,
    GuildRank,
    Oxygen,
    HealthPotionStack,
    MagicPotionStack,
    BackPack0,
    BackPack1,
    BackPack2,
    BackPack3,
    BackPack4,
    BackPack5,
    BackPack6,
    BackPack7,
    HasBackpack,
    Texture,
    InventoryData0,
    InventoryData1,
    InventoryData2,
    InventoryData3,
    InventoryData4,
    InventoryData5,
    InventoryData6,
    InventoryData7,
    InventoryData8,
    InventoryData9,
    InventoryData10,
    InventoryData11,
    InventoryData12,
    InventoryData13,
    InventoryData14,
    InventoryData15,
    InventoryData16,
    InventoryData17,
    InventoryData18,
    InventoryData19,
    PrimaryConstellation,
    SecondaryConstellation,
    PrimaryNodeData,
    SecondaryNodeData,
    DodgeChance,
    CriticalChance,
    CriticalDamage,
    MaxMS,
    MS,
    ManaRegeneration,
    MSRegenRate,
    Armor,
    DamageMultiplier,
    UNUSED,
    StatPoints,
    TimeInCombat,
    MaxHpBonus,
    MaxMpBonus,
    AttackBonus,
    DefenseBonus,
    SpeedBonus,
    DexterityBonus,
    VitalityBonus,
    WisdomBonus,
    DodgeChanceBonus,
    CriticalChanceBonus,
    CriticalDamageBonus,
    MaxMSBonus,
    ManaRegenerationBonus,
    MSRegenRateBonus,
    ArmorBonus,
    DamageBonus,
    UNUSED2,
    AttackSpeed,
    AttackSpeedBonus,
    Condition2,
    AccRank,
    QuestId,
    PartyId,
    AbilityDataA,
    AbilityDataB,
    AbilityDataC,
    AbilityDataD,
    
    //todo: missing/diff name
    Effects,
    Glow,
    AltTextureIndex,
    PortalUsable,
    Skin,

    StatTypeCount, // Don't remove this
    None = byte.MaxValue
}

public enum StatsTypeOld : byte {
    MaximumHp = 0,
    Hp = 1,
    Size = 2,
    MaximumMp = 3,
    Mp = 4,
    ExperienceGoal = 5,
    Experience = 6,
    Level = 7,
    Inventory0 = 8,
    Inventory1 = 9,
    Inventory2 = 10,
    Inventory3 = 11,
    Inventory4 = 12,
    Inventory5 = 13,
    Inventory6 = 14,
    Inventory7 = 15,
    Inventory8 = 16,
    Inventory9 = 17,
    Inventory10 = 18,
    Inventory11 = 19,
    Attack = 20,
    Defense = 21,
    Speed = 22,
    Vitality = 26,
    Wisdom = 27,
    Dexterity = 28,
    Effects = 29,
    Stars = 30,
    Name = 31,
    Texture1 = 32,
    Texture2 = 33,
    MerchantMerchandiseType = 34,
    Credits = 35,
    SellablePrice = 36,
    PortalUsable = 37,
    AccountId = 38,
    CurrentFame = 39,
    SellablePriceCurrency = 40,
    ObjectConnection = 41,
    MerchantRemainingCount = 42,
    MerchantRemainingMinute = 43,
    MerchantDiscount = 44,
    SellableRankRequirement = 45,
    HpBoost = 46,
    MpBoost = 47,
    AttackBonus = 48,
    DefenseBonus = 49,
    SpeedBonus = 50,
    VitalityBonus = 51,
    WisdomBonus = 52,
    DexterityBonus = 53,
    OwnerAccountId = 54,
    NameChangerStar = 55,
    NameChosen = 56,
    Fame = 57,
    FameGoal = 58,
    Glow = 59,
    SinkOffset = 60,
    AltTextureIndex = 61,
    Guild = 62,
    GuildRank = 63,
    OxygenBar = 64,
    HealthStackCount = 65,
    MagicStackCount = 66,
    BackPack0 = 67,
    BackPack1 = 68,
    BackPack2 = 69,
    BackPack3 = 70,
    BackPack4 = 71,
    BackPack5 = 72,
    BackPack6 = 73,
    BackPack7 = 74,
    HasBackpack = 75,
    Skin = 76,

    None = 255
}