using System;
using System.Collections.Immutable;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Alloy.ShaderSourceGen;

[Generator]
public class ShaderGenerator : IIncrementalGenerator {

    private const string AttributeFullName = "Alloy.Common.SourceGen.ShaderAttribute";
    
    private static readonly DiagnosticDescriptor MissingShaderFileDescriptor = new("SHADERGEN001", "Missing shader source file", "Could not find a '{1}' AdditionalFile for shader '{0}'", "ShaderGen", DiagnosticSeverity.Error, isEnabledByDefault: true);

    public void Initialize(IncrementalGeneratorInitializationContext context) {
        var candidates = context.SyntaxProvider.ForAttributeWithMetadataName(AttributeFullName, IsValidNode, ToProperty).Where(static x => x is not null);
        var additionalFiles = context.AdditionalTextsProvider.Collect();
        var combined = candidates.Collect().Combine(additionalFiles);
 
        context.RegisterSourceOutput(combined, static (spc, source) => Execute(source.Left, source.Right, spc));
    }

    private static bool IsValidNode(SyntaxNode node, CancellationToken _) => node is PropertyDeclarationSyntax p && p.Modifiers.Any(SyntaxKind.PartialKeyword);

    private static ShaderProperty ToProperty(GeneratorAttributeSyntaxContext context, CancellationToken _) {
        var propertySymbol = (IPropertySymbol)context.TargetSymbol;
        var propertySyntax = (PropertyDeclarationSyntax)context.TargetNode;
        var containingType = propertySymbol.ContainingType;
        var attribute = context.Attributes[0];
        
        if (attribute.ConstructorArguments.Length == 0 || attribute.ConstructorArguments[0].Value is not string shaderName || string.IsNullOrEmpty(shaderName)) {
            return null;
        }
        
        var modifiers = string.Join(" ", propertySyntax.Modifiers.Select(m => m.Text));

        return new ShaderProperty(shaderName, propertySymbol.Name, modifiers, containingType.Name, containingType.ContainingNamespace.IsGlobalNamespace ? string.Empty : containingType.ContainingNamespace.ToDisplayString());
    }

    private static void Execute(ImmutableArray<ShaderProperty> properties, ImmutableArray<AdditionalText> additionalFiles, SourceProductionContext spc) {
        if (properties.IsDefaultOrEmpty) {
            return;
        }
        
        var hasMissingFiles = false;
 
        foreach (var prop in properties) {
            var vertexFile = TryGetShader(additionalFiles, prop.ShaderName, "vert");
            var fragmentFile = TryGetShader(additionalFiles, prop.ShaderName, "frag");
 
            if (vertexFile is null) {
                spc.ReportDiagnostic(Diagnostic.Create(MissingShaderFileDescriptor, Location.None, prop.ShaderName, "vert"));
                hasMissingFiles = true;
            }
 
            if (fragmentFile is null) {
                spc.ReportDiagnostic(Diagnostic.Create(MissingShaderFileDescriptor, Location.None, prop.ShaderName, "frag"));
                hasMissingFiles = true;
            }
        }
 
        if (hasMissingFiles) {
            return;
        }

        foreach (var group in properties.GroupBy(p => (p.ContainingNamespace, p.ContainingTypeName))) {
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine();

            sb.AppendLine("using Alloy.Common.SourceGen;");
            sb.AppendLine();

            if (!string.IsNullOrEmpty(group.Key.ContainingNamespace)) {
                sb.AppendLine($"namespace {group.Key.ContainingNamespace};");
                sb.AppendLine();
            }

            sb.AppendLine($"partial class {group.Key.ContainingTypeName}");
            sb.AppendLine("{");

            foreach (var prop in group) {
                var vertexText = TryGetShader(additionalFiles, prop.ShaderName, "vert")!.GetText(spc.CancellationToken)?.ToString() ?? string.Empty;
                var fragmentText = TryGetShader(additionalFiles, prop.ShaderName, "frag")!.GetText(spc.CancellationToken)?.ToString() ?? string.Empty;
 
                sb.AppendLine($"    {prop.Modifiers} ShaderSource {prop.PropertyName} => new ShaderSource(\"{prop.ShaderName}\", {AsStringLiteral(vertexText)}, {AsStringLiteral(fragmentText)});");
            }

            sb.AppendLine("}");

            spc.AddSource($"{group.Key.ContainingTypeName}.Shaders.g.cs", sb.ToString());
        }
    }
    
    private static AdditionalText TryGetShader(ImmutableArray<AdditionalText> additionalFiles, string shaderName, string extension) => additionalFiles.FirstOrDefault(file => string.Equals(Path.GetFileNameWithoutExtension(file.Path), shaderName, System.StringComparison.OrdinalIgnoreCase) && string.Equals(Path.GetExtension(file.Path).TrimStart('.'), extension, System.StringComparison.OrdinalIgnoreCase));
    
    private static string AsStringLiteral(string text) {
        int maxRun = 0, current = 0;
        foreach (var c in text) {
            if (c == '"') {
                current++; maxRun = Math.Max(maxRun, current);
            } else {
                current = 0;
            }
        }
 
        var quotes = new string('"', Math.Max(3, maxRun + 1));
        return $"{quotes}\n{text}\n{quotes}";
    }
    
    private class ShaderProperty(string shaderName, string propertyName, string modifiers, string containingTypeName, string containingNamespace) {
        public readonly string ShaderName = shaderName;
        public readonly string PropertyName = propertyName;
        public readonly string Modifiers = modifiers;
        public readonly string ContainingTypeName = containingTypeName;
        public readonly string ContainingNamespace = containingNamespace;
    }

}