<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>disable</Nullable>
        <Authors>Zolmex</Authors>
        <SatelliteResourceLanguages>en</SatelliteResourceLanguages>
    </PropertyGroup>

    <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
        <PlatformTarget>x64</PlatformTarget>
        <OutputPath>../bin/release</OutputPath>
    </PropertyGroup>

    <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
        <OutputPath>../bin/debug</OutputPath>
        <PlatformTarget>AnyCPU</PlatformTarget>
        <DefineConstants>TRACE</DefineConstants>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Newtonsoft.Json" Version="13.0.3"/>
        <PackageReference Include="MinVer" Version="7.0.0">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
    </ItemGroup>

    <PropertyGroup>
        <MinVerTagPrefix>v</MinVerTagPrefix>
        <MinVerDefaultPreReleaseIdentifiers>0</MinVerDefaultPreReleaseIdentifiers>
        <!-- This forces the version to ignore the commit hash -->
        <IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\Common\Common.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <None Update="Handlers\Crossdomain\crossdomain.xml">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
    </ItemGroup>

</Project>
